server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /sessions {
        proxy_pass http://backend:8000;
    }

    location /simulate {
        proxy_pass http://backend:8000;
    }

    location /metrics {
        proxy_pass http://backend:8000;
    }

    location /health {
        proxy_pass http://backend:8000;
    }
}
